---
title: "Analyse_Comportement_Lynx"
output: html_document
---

```{r}
#importation tidyverse

library(readr)
library(tidyr)
library(dplyr)
library(ggplot2)
library(tibble)
library(stringr)
library(forcats)
library(lubridate)

library(emmeans)
library(glmmTMB)
library(bbmle)

library(blme)
library(lme4)
library(lmerTest)
library(MuMIn)

library(performance)
library(ggeffects)

library(ggsignif)

```

```{r}

# Fonction de calcul des indices de surdispersion

overdisp_fun <- function(model) {
  rdf <- df.residual(model)
  rp <- residuals(model,type="pearson")
  Pearson.chisq <- sum(rp^2)
  prat <- Pearson.chisq/rdf
  pval <- pchisq(
    Pearson.chisq, 
    df=rdf, 
    lower.tail=FALSE
  )
  c(
    chisq=Pearson.chisq,
    ratio=prat,
    rdf=rdf,
    p=pval
  )
}

```

```{r}
Tidy_Comportement <- read_csv("Data/Tidy_Comportement.csv")

Tidy_Comportement$PE <- as.factor(Tidy_Comportement$PE)
Tidy_Comportement$TypePiege <- as.factor(Tidy_Comportement$TypePiege)
Tidy_Comportement$TypeLieu <- as.factor(Tidy_Comportement$TypeLieu)
Tidy_Comportement$Odorant <- as.factor(Tidy_Comportement$Odorant)
Tidy_Comportement$Support <- as.factor(Tidy_Comportement$Support)

Tidy_Comportement$MS <- as.factor(Tidy_Comportement$MS)
Tidy_Comportement$PP <- as.factor(Tidy_Comportement$PP)
Tidy_Comportement$MSPP <- as.factor(Tidy_Comportement$MSPP)
Tidy_Comportement$Identifiant <- as.factor(Tidy_Comportement$Identifiant)

Tidy_Comportement = Tidy_Comportement %>% 
  filter(Identifiant != "Indetermine")

head(Tidy_Comportement)
```

# GLMM : Modèle ombrelle

sélection de la structure aléatoire

```{r}
modele_ombrelle1 <- bglmer( # utilisation de bglmer car cela permet d'avoir une convergence malgré une séparation complètre des variables
  Frottement ~ 
    PE + 
    TypePiege + 
    Odorant +
    ecart_attractif +
    Support + 
    TypeLieu + 
    (1 | MS),
  data = Tidy_Comportement,
  family = binomial,
  fixef.prior = normal(sd = 10)  # prior faible sur les coefficients fixes
)

modele_ombrelle2 <- bglmer( # utilisation de bglmer car cela permet d'avoir une convergence malgré une séparation complètre des variables
  Frottement ~ 
    PE + 
    TypePiege + 
    Odorant +
    ecart_attractif +
    Support + 
    TypeLieu + 
    (1 | PP),
  data = Tidy_Comportement,
  family = binomial,
  fixef.prior = normal(sd = 10)  # prior faible sur les coefficients fixes
)

modele_ombrelle3 <- bglmer( # utilisation de bglmer car cela permet d'avoir une convergence malgré une séparation complètre des variables
  Frottement ~ 
    PE + 
    TypePiege + 
    Odorant +
    ecart_attractif +
    Support + 
    TypeLieu + 
    (1 | Identifiant),
  data = Tidy_Comportement,
  family = binomial,
  fixef.prior = normal(sd = 10)  # prior faible sur les coefficients fixes
)

modele_ombrelle4 <- bglmer( # utilisation de bglmer car cela permet d'avoir une convergence malgré une séparation complètre des variables
  Frottement ~ 
    PE + 
    TypePiege + 
    Odorant +
    ecart_attractif +
    Support + 
    TypeLieu + 
    (1 | MS/PP),
  data = Tidy_Comportement,
  family = binomial,
  fixef.prior = normal(sd = 10)  # prior faible sur les coefficients fixes
)

modele_ombrelle5 <- bglmer( # utilisation de bglmer car cela permet d'avoir une convergence malgré une séparation complètre des variables
  Frottement ~ 
    PE + 
    TypePiege + 
    Odorant +
    ecart_attractif +
    Support + 
    TypeLieu + 
    (1 | MS/Identifiant),
  data = Tidy_Comportement,
  family = binomial,
  fixef.prior = normal(sd = 10)  # prior faible sur les coefficients fixes
)

modele_ombrelle6 <- bglmer( # utilisation de bglmer car cela permet d'avoir une convergence malgré une séparation complètre des variables
  Frottement ~ 
    PE + 
    TypePiege + 
    Odorant +
    ecart_attractif +
    Support + 
    TypeLieu + 
    (1 | PP/Identifiant),
  data = Tidy_Comportement,
  family = binomial,
  fixef.prior = normal(sd = 10)  # prior faible sur les coefficients fixes
)

modele_ombrelle7 <- bglmer( # utilisation de bglmer car cela permet d'avoir une convergence malgré une séparation complètre des variables
  Frottement ~ 
    PE + 
    TypePiege + 
    Odorant +
    ecart_attractif +
    Support + 
    TypeLieu + 
    (1 | MS/PP/Identifiant),
  data = Tidy_Comportement,
  family = binomial,
  fixef.prior = normal(sd = 10)  # prior faible sur les coefficients fixes
)

AICc(modele_ombrelle1)
AICc(modele_ombrelle2)
AICc(modele_ombrelle3)
AICc(modele_ombrelle4)
AICc(modele_ombrelle5)
AICc(modele_ombrelle6)
AICc(modele_ombrelle7)


```

La meilleur structure aléatoire est donc $(1|MS)$

```{r}
modele_ombrelle <- bglmer( # utilisation de bglmer car cela permet d'avoir une convergence malgré une séparation complètre des variables
  Frottement ~ 
    PE + 
    TypePiege + 
    Odorant +
    ecart_attractif +
    Support + 
    TypeLieu + 
    (1 | MS),
  data = Tidy_Comportement,
  family = binomial,
  fixef.prior = normal(sd = 10)  # prior faible sur les coefficients fixes
)

summary(modele_ombrelle)
```

## AICc et sélection des modèles

Générations des modèles à partir du modèle ombrelle :

```{r}
options(na.action = "na.fail")
modeles_AICc = dredge(
  modele_ombrelle,
  evaluate = TRUE, 
  trace = 2
  )
```

Récupération des meilleurs modèles ayant : $\Delta AICc <2$

```{r}
modeles_selection = get.models(
  modeles_AICc, 
  subset = delta < 2)

length(modeles_selection) #nombre de modeles retenus
```

Meilleur modèle :

```{r}
meilleur_modele = modeles_selection[[1]]

summary(meilleur_modele)
overdisp_fun(meilleur_modele)
r2(meilleur_modele)
```

# Moyennage des modèles :

```{r}
moy_modeles = model.avg(modeles_selection)
summary(moy_modeles)
```

## Essaie suivant

```{r}
modele_ombrelle <- bglmer(
  Frottement ~ 
    TypePiege + 
    TypeLieu + 
    (1 | MS),
  data = Tidy_Comportement,
  family = binomial,
  fixef.prior = normal(sd = 10)  # prior faible sur les coefficients fixes
)

summary(modele_ombrelle)
overdisp_fun(modele_ombrelle)

```

```{r}
options(na.action = "na.fail")
modeles_AICc = dredge(
  modele_ombrelle,
  evaluate = TRUE, 
  trace = 2
  )
```

```{r}
modeles_selection = get.models(
  modeles_AICc, 
  subset = delta < 2)

length(modeles_selection) #nombre de modeles retenus
```

```{r}
meilleur_modele = modeles_selection[[1]]

summary(meilleur_modele)
overdisp_fun(meilleur_modele)
r2(meilleur_modele)
```

```{r}
moy_modeles = model.avg(modeles_selection)
summary(moy_modeles)
```
