---
title: "AnalyseGenotypage"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Import librairies

```{r}
#importation tidyverse

library(readr)
library(tidyr)
library(dplyr)
library(ggplot2)
library(tibble)
library(stringr)
library(forcats)
library(lubridate)

library(emmeans)
library(glmmTMB)
library(bbmle)

library(blme)
library(lme4)
library(lmerTest)
library(MuMIn)

library(performance)
library(ggeffects)

library(car)
library(ggsignif)

```

## Import des données

```{r}

Tidy_Genotype <- read_csv("Data/Tidy_Genotype.csv") %>% 
  mutate(
    #duree_exposition = as.factor(duree_expostion),
    nombre_bulbes = as.factor(nombre_bulbes)       
  )

head(Tidy_Genotype)

```

# GLMM

```{r}

modele_ombrelle = glm(
  succes_genotypage ~
    duree_exposition +
    nombre_bulbes +
    duree_exposition:nombre_bulbes +
    conditions_exposition:nombre_bulbes +
    conditions_exposition:duree_exposition +
    conditions_exposition,
  data = Tidy_Genotype,
  family = poisson
)

AICc(modele_ombrelle1)
summary(modele_ombrelle)

```

Calcul du $\hat{C}$ du modèle ombrelle

```{r}

overdisp_fun <- function(model) {
  rdf <- df.residual(model)
  rp <- residuals(model,type="pearson")
  Pearson.chisq <- sum(rp^2)
  prat <- Pearson.chisq/rdf
  pval <- pchisq(
    Pearson.chisq, 
    df=rdf, 
    lower.tail=FALSE
  )
  c(
    chisq=Pearson.chisq,
    ratio=prat,
    rdf=rdf,
    p=pval
  )
}


overdisp_fun(modele_ombrelle)

```

## AICc et sélection des modèles

Générations des modèles

```{r}
options(na.action = "na.fail")
modeles_AICc = dredge(modele_ombrelle)

head(modeles_AICc)
```

Récupération des meilleurs modèles ie $\Delta AICc <2$

```{r}
modeles_selection = get.models(
  modeles_AICc, 
  subset = delta < 2)

length(modeles_selection) #nombre de modeles retenus
```

Meilleur modèle:

```{r}

meilleur_modele = modeles_selection[[1]]
summary(meilleur_modele)

# Surdispersion du meilleure modele

overdisp_fun(meilleur_modele)

# R² meilleur modele  

r2(meilleur_modele)

```

Moyennage des modèles

```{r}
moy_modeles = model.avg(modeles_selection)
summary(moy_modeles)
```


```{r}
modele_final = glm(
  succes_genotypage ~ 
    duree_exposition,
  data = Tidy_Genotype
)
Anova(modele_final, type = "III")


ggplot(
    data = Tidy_Genotype
  ) +
  geom_point(
    aes(
      x = duree_exposition,
      y = succes_genotypage,
    ),
    position = "jitter"
  )

pred <- ggpredict(modele_final, terms = "duree_exposition")

# Tracé
ggplot(pred, aes(x = x, y = predicted)) +
  geom_line() + 
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), alpha = 0.2) +
  geom_point(data = Tidy_Genotype, aes(x = duree_exposition, y = succes_genotypage), 
             position = position_jitter(height = 0.02, width = 0)) +
  labs(y = "Genotyping success prediction", x = "Exposition time") +
  theme_bw()

ggsave("Plots/Prediction_bite.png")
```

