---
title: "Analyse_Releves_PP_GLMM"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Import librairies

```{r}
#importation tidyverse

library(readr)
library(tidyr)
library(dplyr)
library(ggplot2)
library(tibble)
library(stringr)
library(forcats)
library(lubridate)

library(emmeans)
library(glmmTMB)
library(bbmle)

library(lme4)
library(lmerTest)
library(MuMIn)

library(ggsignif)

```

## Import données

```{r}
Tidy_Releves_PP <- read_csv("Data/Tidy_Releves_PP.csv")

Tidy_Releves_PP$MSPP <- as.factor(Tidy_Releves_PP$MSPP)
Tidy_Releves_PP$PP <- as.factor(Tidy_Releves_PP$PP)
Tidy_Releves_PP$MS <- as.factor(Tidy_Releves_PP$MS)
Tidy_Releves_PP$PE <- as.factor(Tidy_Releves_PP$PE)

head(Tidy_Releves_PP)

```

# GLMMs

## Modèle ombrelle

  Définition du modèle ombrelle

```{r}
modele_ombrelle <- glmmTMB(
  DetectionLynx ~ 
    TypePiege + 
    TypeLieu + 
    PE + 
    Support + 
    Hauteur_cm + 
    DistanceItineraire_cm + 
    DistanceBorne_cm + 
    (1 | MS / MSPP),
  data = Tidy_Releves_PP,
  family = binomial
  )

summary(modele_ombrelle)

```

  Calcul du $\hat{C}$ du modèle ombrelle

```{r}

overdisp_fun <- function(model) {
  rdf <- df.residual(model)
  rp <- residuals(model,type="pearson")
  Pearson.chisq <- sum(rp^2)
  prat <- Pearson.chisq/rdf
  pval <- pchisq(
    Pearson.chisq, 
    df=rdf, 
    lower.tail=FALSE
  )
  c(
    chisq=Pearson.chisq,
    ratio=prat,
    rdf=rdf,
    p=pval
  )
}


overdisp_fun(modele_ombrelle)

```

## AICc et sélection des modèles

  Générations des modèles

```{r}
options(na.action = "na.fail")
modeles_AICc = dredge(modele_ombrelle)
```

  Récupération des meilleurs modèles ie $\Delta AICc <2$

```{r}
modeles_selection = get.models(
  modeles_AICc, 
  subset = delta < 2)

length(modeles_selection) #nombre de modeles retenus
```

  Moyennage des modèles

```{r}
moy_modeles = model.avg(modeles_selection)
summary(moy_modeles)
```

