---
title: "Analyse_Releves_PP_GLMM_interaction"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Import librairies

```{r}
#importation tidyverse

library(readr)
library(tidyr)
library(dplyr)
library(ggplot2)
library(tibble)
library(stringr)
library(forcats)
library(lubridate)

library(emmeans)
library(glmmTMB)
library(bbmle)

library(blme)
library(lme4)
library(lmerTest)
library(MuMIn)

library(performance)
library(ggeffects)

library(ggsignif)

```

## Import données

```{r}
Tidy_Releves_PP <- read_csv("Data/Tidy_Releves_PP.csv")

Tidy_Releves_PP$MSPP <- as.factor(Tidy_Releves_PP$MSPP)
Tidy_Releves_PP$PP <- as.factor(Tidy_Releves_PP$PP)
Tidy_Releves_PP$MS <- as.factor(Tidy_Releves_PP$MS)
Tidy_Releves_PP$PE <- as.factor(Tidy_Releves_PP$PE)

# retirer les données Urine

Tidy_Releves_PP = 
  Tidy_Releves_PP %>% 
  filter(Odorant != "Urine")

head(Tidy_Releves_PP) 

```

# GLMMs

## Modèle ombrelle

Définition du modèle ombrelle

```{r}
modele_ombrelle <- glmmTMB(
  DetectionLynx ~ 
    TypePiege +
    Support +
    PE +
    (1 | MS/MSPP),
  data = Tidy_Releves_PP,
  family = binomial
  )

summary(modele_ombrelle)
r2(modele_ombrelle)

```

Calcul du $\hat{C}$ du modèle ombrelle

```{r}

overdisp_fun <- function(model) {
  rdf <- df.residual(model)
  rp <- residuals(model,type="pearson")
  Pearson.chisq <- sum(rp^2)
  prat <- Pearson.chisq/rdf
  pval <- pchisq(
    Pearson.chisq, 
    df=rdf, 
    lower.tail=FALSE
  )
  c(
    chisq=Pearson.chisq,
    ratio=prat,
    rdf=rdf,
    p=pval
  )
}


overdisp_fun(modele_ombrelle)
```

## AICc et sélection des modèles

Générations des modèles

```{r}
options(na.action = "na.fail")
modeles_AICc = dredge(modele_ombrelle)

head(modeles_AICc)
```

Récupération des meilleurs modèles ie $\Delta AICc <2$

```{r}
modeles_selection = get.models(
  modeles_AICc, 
  subset = delta < 2)

length(modeles_selection) #nombre de modeles retenus
```

Meilleur modèle:

```{r}

meilleur_modele = modeles_selection[[1]]
summary(meilleur_modele)

# Surdispersion du meilleure modele

overdisp_fun(meilleur_modele)

# R² marginale 

r.squaredGLMM(meilleur_modele)
r2(meilleur_modele)
```

Moyennage des modèles

```{r}
moy_modeles = model.avg(modeles_selection)
summary(moy_modeles)
```

```{r}

# TypePiege

resultatsTypePiege<- lapply(
  modeles_selection, 
  function(m) {
    tryCatch(
      emmeans(
        m, 
        pairwise ~ TypePiege
        ),
      error = function(e) NULL  # retourne NULL si Odorant absent du modèle
    )
  }
)

# Support

resultatsSupport <- lapply(
  modeles_selection, 
  function(m) {
    tryCatch(
      emmeans(
        m, 
        pairwise ~ Support
        ),
      error = function(e) NULL  # retourne NULL si Odorant absent du modèle
    )
  }
)

# PE

resultatsPE <- lapply(
  modeles_selection, 
  function(m) {
    tryCatch(
      emmeans(
        m, 
        pairwise ~ PE
        ),
      error = function(e) NULL  # retourne NULL si Odorant absent du modèle
    )
  }
)

## Résultats

resultatsPE
resultatsSupport
resultatsTypePiege

#r.squaredGLMM(moy_modeles), marche pas parce que c'est pas un glmmTMB
r2(moy_modeles)

```

```{r}

modele_signif = glmmTMB(
  DetectionLynx ~
    TypePiege +
    Support +
    PE +
    (1|MS),
  data = Tidy_Releves_PP,
  family = binomial
)
summary(modele_signif)


pred <- ggpredict(
  modele_signif, 
  terms = c(
    "TypePiege",
    "Support"
  ), 
  bias_correction = TRUE
  )
plot(pred)


```


