---
title: "Analyse_Releves_PP"
output: html_document
date: "2026-05-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Import librairies

```{r}
#importation tidyverse

library(readr)
library(tidyr)
library(dplyr)
library(ggplot2)
library(tibble)
library(stringr)
library(forcats)
library(lubridate)

library(emmeans)
library(glmmTMB)
library(bbmle)

library(ggsignif)

```

## Import données

```{r}
Tidy_Releves_PP <- read_csv("Data/Tidy_Releves_PP.csv")
View(Tidy_Releves_PP)
```

## 1ère Visualisation

Pour l'influence du type de pièges

```{r}

modele <- glm(
  DetectionLynx ~ TypePiege,
  data = Tidy_Releves_PP,
  family = binomial
)
emmeans(
  modele,
  pairwise ~ TypePiege
)

ggplot(
  data = Tidy_Releves_PP, 
  aes(
    x = TypePiege, 
    y = DetectionLynx
    )
  ) +
  stat_summary(
    fun = mean,
    geom = "bar", 
    width = 0.5, 
    show.legend = FALSE, 
    fill = "grey", 
    colour="black"
  ) +
  stat_summary(
    fun.data = mean_se, 
    geom = "errorbar",
    width = 0.2
  ) +
  scale_y_continuous(
    labels = scales::percent
  ) +
  labs(
    x     = "Type de piège",
    y     = "Probabilité d'obtention de poils de lynx",
    title = "Comparaison des types de pièges à poils"
  ) +
  theme_bw()

ggsave(
  filename = "Plots/CompTypePiegePoils.png"
)



```

Pour l'influence du type de support :

```{r}
modele <- glm(
  DetectionLynx ~ Support,
  data = Tidy_Releves_PP,
  family = binomial
)
emmeans(
  modele,
  pairwise ~ Support
)


ggplot(Tidy_Releves_PP, aes(x = Support, y = DetectionLynx)) +
  stat_summary(fun = mean, geom = "bar", width = 0.5, show.legend = FALSE, fill = "grey", colour="black") +
  stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.2) +
  scale_y_continuous(labels = scales::percent) +
  labs(
    x     = "Type de support",
    y     = "Probabilité d'obtention de poils de lynx",
    title = "Comparaisons des types de support de pièges à poil"
  ) +
  theme_bw()

ggsave(
  filename = "Plots/CompTypeSupport.png"
)

```

Pour l'influence de l'odorant :

```{r}
modele <- glm(
  DetectionLynx ~ Odorant,
  data = Tidy_Releves_PP,
  family = binomial
)
emmeans(
  modele,
  pairwise ~ Odorant
)

ggplot(Tidy_Releves_PP, aes(x = Odorant, y = DetectionLynx)) +
  stat_summary(fun = mean, geom = "bar", width = 0.5, show.legend = FALSE, fill = "grey", colour="black") +
  stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.2) +
  scale_y_continuous(labels = scales::percent) +
  labs(
    x     = "Type d'odorant",
    y     = "Probabilité d'obtention de poils de lynx",
    title = "Comparaisons des odorants"
  ) +
  theme_bw()

ggsave(
  filename = "Plots/CompOdorants.png"
)

```

Pour l'influence de la période :

```{r}
modele <- glm(
  DetectionLynx ~ as.factor(PE),
  data = Tidy_Releves_PP,
  family = binomial
)
emmeans(
  modele,
  pairwise ~ PE
)


ggplot(Tidy_Releves_PP, aes(x = as.factor(PE), y = DetectionLynx)) +
  stat_summary(fun = mean, geom = "bar", width = 0.5, show.legend = FALSE, fill = "grey", colour="black") +
  stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.2) +
  scale_y_continuous(labels = scales::percent) +
  labs(
    x     = "Période",
    y     = "Probabilité d'obtention de poils de lynx",
    title = "Comparaisons des périodes"
  ) +
  theme_bw()

ggsave(
  filename = "Plots/CompPeriode.png"
)
```

Pour l'influence du type de lieu

```{r}
modele <- glm(
  DetectionLynx ~ TypeLieu,
  data = Tidy_Releves_PP,
  family = binomial
)
emmeans(
  modele,
  pairwise ~ TypeLieu
)


ggplot(Tidy_Releves_PP, aes(x = TypeLieu, y = DetectionLynx)) +
  stat_summary(fun = mean, geom = "bar", width = 0.5, show.legend = FALSE, fill = "grey", colour="black") +
  stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.2) +
  scale_y_continuous(labels = scales::percent) +
  labs(
    x     = "Période",
    y     = "Probabilité d'obtention de poils de lynx",
    title = "Comparaisons des périodes"
  ) +
  theme_bw()

ggsave(
  filename = "Plots/CompTypeLieu.png"
)
```
Pour l'influence de la hauteur du piège :

```{r}
modele <- glm(
  DetectionLynx ~ Hauteur_cm,
  data = Tidy_Releves_PP,
  family = binomial
)
summary(modele)



ggplot(
  data = Tidy_Releves_PP,
  aes(
    x = as.factor(DetectionLynx),
    y = Hauteur_cm
    )
  ) +
  geom_boxplot() +
  labs(
    x     = "Detection",
    y     = "Hauteur",
    title = "Comparaisons des hauteurs"
  ) +
  theme_bw()
  
```

Pour l'influence de la distance à l'itinéraire du lynx :

```{r}
modele <- glm(
  DetectionLynx ~ DistanceItineraire_cm,
  data = Tidy_Releves_PP,
  family = binomial
)
summary(modele)


ggplot(
  data = Tidy_Releves_PP,
  aes(
    x = as.factor(DetectionLynx),
    y = DistanceItineraire_cm
    )
  ) +
  geom_boxplot() +
  labs(
    x     = "Detection",
    y     = "Distance à l'itinéraire",
    title = "Comparaisons des distances à l'itinéraire"
  ) +
  theme_bw()
  
```

