---
title: "Formatage_Donnees_Brutes_Genotypages"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# **ANALYSE PAR GLMM DES DONNEES DE RELEVES DE PIEGE A POIL**

## Import librairies

```{r}
#importation tidyverse

library(readr)
library(tidyr)
library(dplyr)
library(ggplot2)
library(tibble)
library(stringr)
library(forcats)
library(lubridate)

library(emmeans)
library(glmmTMB)
library(bbmle)

library(blme)
library(lme4)
library(lmerTest)
library(MuMIn)

library(performance)
library(ggeffects)

library(ggsignif)

```

# Import du tableau

```{r}

consensus_data <- read_delim(
  "Data/consensus_data.csv", 
  delim = ";", 
  escape_double = FALSE, 
  trim_ws = TRUE)
head(consensus_data)

proben_data <- read_delim(
  "Data/proben_data.csv",
  delim = ";", escape_double = FALSE,
  trim_ws = TRUE
  )
head(proben_data)

echantillons_data <- read_csv("Data/echantillons_data.csv")
head(echantillons_data)


```

# Tidyfication 

```{r}

echantillons_data = echantillons_data %>% 
  mutate(
    Gen_ID = NA
  )

for(i in 1:nrow(echantillons_data)){
  echantillon_ID = echantillons_data$N_echantillon_seckenberg[i]
  gen_id = proben_data$LabId[proben_data$Beschriftung==echantillon_ID]
  echantillons_data$Gen_ID[i] = gen_id
}

head(echantillons_data)

##

Tidy_Genotype = consensus_data %>% 
  filter(
    Pop == "Cons"
  ) %>%
  left_join(
    echantillons_data %>% 
      select(
        Gen_ID, 
        conditions_exposition, 
        duree_exposition, 
        nombre_bulbes
        ),
    by = c(
      "GEN_ID" = "Gen_ID"
      )
  ) %>% 
  mutate(
    across(
      FCA126a:Fzfb, 
      ~ if_else(
        . > 0
        , 1
        , 0
        )
      )
  )

head(Tidy_Genotype)
``` 

