---
title: "Formatage_Donnees_Brutes"
output: html_document
date: "2026-05-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Importation des librairies utiles :

```{r}

#importation tidyverse

library(readr)
library(tidyr)
library(dplyr)
library(ggplot2)
library(tibble)
library(stringr)
library(forcats)
library(lubridate)

```

## Importation des données brutes :

```{r}

Releves_PP <- read_csv("Data/Releves_PP.csv")
View(Releves_PP)

```

## Tidyfication des données

```{r}
Releves_PP = Releves_PP %>% 
  mutate(DetectionLynx = if_else(
    Nbr_poil_lynx>0,
    1,
    0)) %>% 
  replace_na(list(
    Nbr_poil = 0,
    Nbr_poil_lynx = 0,
    Nbr_poil_lynx_bulbe = 0,
    Nbr_poil_lynx_jarre = 0,
    NumDetectLynx = 0,
    DetectionLynx = 0
  )) %>% 
  mutate(Pose_attractif = if_else(
    Pose_attractif=="OUI",
    1,
    0)) %>% 
  select(MS,
         PP,
         MSPP,
         PE,
         Date,
         Pose_attractif,
         `date attractif`,
         `ecart attractif`,
         DetectionLynx,
         Nbr_poil_lynx)
```

## Ajout des caractéristiques des PP

# Importation des caractéristiques des PP

```{r}

Description_PP <- read_csv("Data/Description_PP.csv")
View(Description_PP)

```

# Ajout des caractéristiques

```{r}

Releves_PP = Releves_PP %>% 
  mutate(Odorant = NA,
         TypePiege = NA,
         Support = NA,
         Hauteur_cm = NA,
         DistanceBorne_cm = NA,
         DistanceItineraire_cm = NA,
         TypeLieu = NA)

n = nrow(Releves_PP)

for(i in 1:n){
  index = as.numeric(Releves_PP[i,3])
  Releves_PP[i,11] = Description_PP$Odorant[Description_PP$MSPP == index]
  Releves_PP[i,12] = Description_PP$Piege_poils[Description_PP$MSPP == index]
  Releves_PP[i,13] = Description_PP$support_utilise[Description_PP$MSPP == index]
  Releves_PP[i,14] = Description_PP$`Hauteur_sol au_sol`[Description_PP$MSPP == index]
  Releves_PP[i,15] = Description_PP$distance_borne_marquage[Description_PP$MSPP == index]
  Releves_PP[i,16] = Description_PP$distance_itineraire_lynx[Description_PP$MSPP == index]
  Releves_PP[i,17] = Description_PP$Type[Description_PP$MSPP == index]

}

```

## Export des données traitées

```{r}

write_csv(Releves_PP,file = "Data/Tidy_Releves_PP.csv")

```


