---
title: "Site_Occupancy"
output: html_document
---

## Import librairies

```{r}
#importation tidyverse

library(readr)
library(tidyr)
library(dplyr)
library(ggplot2)
library(tibble)
library(stringr)
library(forcats)
library(lubridate)

#importation des autres librairies

library(emmeans)
library(glmmTMB)
library(bbmle)

library(blme)
library(lme4)
library(lmerTest)
library(MuMIn)

library(performance)
library(ggeffects)

library(ggsignif)

library(car)

library(unmarked)

```

## Fonctions utiles

```{r}

# Fonction de calcul des indices de surdispersion

overdisp_fun <- function(model) {
  rdf <- df.residual(model)
  rp <- residuals(model,type="pearson")
  Pearson.chisq <- sum(rp^2)
  prat <- Pearson.chisq/rdf
  pval <- pchisq(
    Pearson.chisq, 
    df=rdf, 
    lower.tail=FALSE
  )
  c(
    chisq=Pearson.chisq,
    ratio=prat,
    rdf=rdf,
    p=pval
  )
}

```

## Import des données

```{r}
dat <- read_csv("Data/Tidy_Site_Occupancy.csv")
head(dat)

site_covs = read_csv("Data/caracteristiques_MS.csv")
head(site_covs)

ecart_attractif = read_csv("Data/Tidy_Ecart_Attractif.csv")
head(ecart_attractif)

effort_capture = read_csv("Data/Tidy_Effort_Capture.csv")
head(effort_capture)
```

```{r}
 
umf = unmarkedFrameOccu(y = dat,
                        siteCovs = site_covs,
                        obsCovs = list(
                          effort_capture = effort_capture,
                          ecart_attractif = ecart_attractif
                          )
                        )
summary(umf)
```
```{r}
modele = occu(
  ~ scale(effort_capture) 
  ~ 1,
  data = umf,
  linkPsi = "logit",
)

summary(modele)
```

